CREATE TYPE public.check_status AS ENUM ('EN_CARTERA', 'DEPOSITADO', 'ACREDITADO', 'RECHAZADO', 'ENDOSADO', 'ANULADO');
CREATE TYPE public.invoice_status AS ENUM ('EMITIDA', 'ANULADA');
CREATE TYPE public.invoice_type AS ENUM ('A', 'B', 'C');
CREATE TYPE public.notification_kind AS ENUM ('LINK_SEGUIMIENTO', 'CAMBIO_ESTADO', 'COTIZACION', 'FACTURA', 'CAMBIO_PRECIO', 'RETENCION_PENDIENTE');
CREATE TYPE public.notification_status AS ENUM ('PENDIENTE', 'ENVIADO', 'FALLIDO', 'DESCARTADO');
CREATE TYPE public.payment_method_kind AS ENUM ('EFECTIVO', 'BANCO', 'CARTERA_CHEQUES');
CREATE TYPE public.payment_order_status AS ENUM ('REGISTRADA', 'ANULADA');
CREATE TYPE public.payment_value_kind AS ENUM ('MEDIO_PAGO', 'CHEQUE_ENDOSADO', 'RETENCION', 'SALDO_A_FAVOR');
CREATE TYPE public.provisional_credit_note_status AS ENUM ('PENDIENTE', 'FORMALIZADA');
CREATE TYPE public.purchase_doc_type AS ENUM ('FACTURA', 'NOTA_CREDITO', 'NOTA_DEBITO');
CREATE TYPE public.purchase_extraction_status AS ENUM ('EXTRAIDO', 'CONFIRMADO', 'DESCARTADO', 'ERROR');
CREATE TYPE public.purchase_kind AS ENUM ('ARTICULOS', 'CONCEPTOS');
CREATE TYPE public.purchase_letter AS ENUM ('A', 'B', 'C', 'M');
CREATE TYPE public.purchase_status AS ENUM ('REGISTRADA', 'ANULADA');
CREATE TYPE public.quotation_status AS ENUM ('EMITIDA', 'ENVIADA', 'ACEPTADA', 'RECHAZADA');
CREATE TYPE public.receipt_change_kind AS ENUM ('MEDIO_PAGO', 'CHEQUE_PROPIO', 'CHEQUE_ENDOSADO');
CREATE TYPE public.receipt_status AS ENUM ('REGISTRADO', 'ANULADO');
CREATE TYPE public.receipt_value_kind AS ENUM ('MEDIO_PAGO', 'CHEQUE', 'RETENCION', 'SALDO_A_FAVOR');
CREATE TYPE public.tax_base AS ENUM ('NETO', 'TOTAL');
CREATE TYPE public.tax_kind AS ENUM ('IVA', 'PERCEPCION', 'IMPUESTO_INTERNO', 'RETENCION');
CREATE TYPE public.treasury_movement_type AS ENUM ('EGRESO', 'INGRESO', 'TRANSFERENCIA');
CREATE TYPE public.treasury_status AS ENUM ('REGISTRADO', 'ANULADO');
CREATE TYPE public.vehicle_intake_status AS ENUM ('PENDIENTE', 'COTIZADO', 'CERRADO');
