ALTER TABLE ONLY public.ai_credentials ADD CONSTRAINT ai_credentials_pkey PRIMARY KEY (provider);
ALTER TABLE ONLY public.ai_credentials ADD CONSTRAINT ai_credentials_provider_check CHECK ((provider = ANY (ARRAY['GEMINI'::text, 'ANTHROPIC'::text])));
ALTER TABLE ONLY public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE ONLY public.arca_credentials ADD CONSTRAINT arca_credentials_pkey PRIMARY KEY (proposito);
ALTER TABLE ONLY public.arca_credentials ADD CONSTRAINT arca_credentials_cuit_check CHECK ((cuit ~ '^[0-9]{11}$'::text));
ALTER TABLE ONLY public.arca_credentials ADD CONSTRAINT arca_credentials_proposito_check CHECK ((proposito = ANY (ARRAY['PADRON'::text, 'FACTURACION'::text])));
ALTER TABLE ONLY public.arca_tickets ADD CONSTRAINT arca_tickets_pkey PRIMARY KEY (servicio);
ALTER TABLE ONLY public.article_code_sequences ADD CONSTRAINT article_code_sequences_pkey PRIMARY KEY (code_prefix);
ALTER TABLE ONLY public.article_code_sequences ADD CONSTRAINT article_code_sequences_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_combo_article_id_component_article_id_key UNIQUE (combo_article_id, component_article_id);
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_check CHECK ((combo_article_id <> component_article_id));
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_quantity_check CHECK ((quantity > 0));
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_combo_article_id_fkey FOREIGN KEY (combo_article_id) REFERENCES articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_components ADD CONSTRAINT article_components_component_article_id_fkey FOREIGN KEY (component_article_id) REFERENCES articles(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.article_suppliers ADD CONSTRAINT article_suppliers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article_suppliers ADD CONSTRAINT article_suppliers_article_id_supplier_id_key UNIQUE (article_id, supplier_id);
ALTER TABLE ONLY public.article_suppliers ADD CONSTRAINT article_suppliers_purchase_price_check CHECK ((purchase_price >= (0)::numeric));
ALTER TABLE ONLY public.article_suppliers ADD CONSTRAINT article_suppliers_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_suppliers ADD CONSTRAINT article_suppliers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_code_key UNIQUE (code);
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_markup_percent_check CHECK (((markup_percent IS NULL) OR (markup_percent >= (0)::numeric)));
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_stock_quantity_check CHECK ((stock_quantity >= (0)::numeric));
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_unit_price_check CHECK ((unit_price >= (0)::numeric));
ALTER TABLE ONLY public.banks ADD CONSTRAINT banks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.banks ADD CONSTRAINT banks_code_key UNIQUE (code);
ALTER TABLE ONLY public.company_settings ADD CONSTRAINT company_settings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.company_settings ADD CONSTRAINT company_settings_id_check CHECK (id);
ALTER TABLE ONLY public.company_settings ADD CONSTRAINT company_settings_sales_point_check CHECK (((sales_point >= 1) AND (sales_point <= 99999)));
ALTER TABLE ONLY public.company_settings ADD CONSTRAINT company_settings_tax_condition_check CHECK ((tax_condition = ANY (ARRAY['RESPONSABLE_INSCRIPTO'::text, 'MONOTRIBUTO'::text, 'EXENTO'::text, 'CONSUMIDOR_FINAL'::text])));
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_tax_condition_check CHECK ((tax_condition = ANY (ARRAY['RESPONSABLE_INSCRIPTO'::text, 'MONOTRIBUTO'::text, 'EXENTO'::text, 'CONSUMIDOR_FINAL'::text])));
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_profile_id_key UNIQUE (profile_id);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_hourly_cost_check CHECK ((hourly_cost >= (0)::numeric));
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_workplace_check CHECK (((workplace IS NULL) OR (workplace = ANY (ARRAY['Laboratorio 1'::text, 'Laboratorio 2'::text, 'Playa'::text]))));
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.expense_concepts ADD CONSTRAINT expense_concepts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.expense_concepts ADD CONSTRAINT expense_concepts_name_key UNIQUE (name);
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_subtotal_check CHECK ((subtotal >= (0)::numeric));
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.invoice_sequences ADD CONSTRAINT invoice_sequences_pkey PRIMARY KEY (invoice_type, sales_point);
ALTER TABLE ONLY public.invoice_sequences ADD CONSTRAINT invoice_sequences_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_invoice_type_sales_point_number_key UNIQUE (invoice_type, sales_point, number);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_anulada_con_motivo CHECK ((((status = 'ANULADA'::invoice_status) AND (voided_at IS NOT NULL) AND (voided_reason IS NOT NULL)) OR ((status = 'EMITIDA'::invoice_status) AND (voided_at IS NULL) AND (voided_reason IS NULL))));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_net_amount_check CHECK ((net_amount >= (0)::numeric));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_paid_amount_check CHECK ((paid_amount >= (0)::numeric));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_payment_terms_days_check CHECK ((payment_terms_days >= 0));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_total_amount_check CHECK ((total_amount >= (0)::numeric));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_vat_amount_check CHECK ((vat_amount >= (0)::numeric));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.notification_templates ADD CONSTRAINT notification_templates_pkey PRIMARY KEY (status_id);
ALTER TABLE ONLY public.notification_templates ADD CONSTRAINT notification_templates_status_id_fkey FOREIGN KEY (status_id) REFERENCES work_order_statuses(id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_dedupe_key_key UNIQUE (dedupe_key);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_receipt_value_id_fkey FOREIGN KEY (receipt_value_id) REFERENCES receipt_values(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payment_methods ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_methods ADD CONSTRAINT payment_methods_name_key UNIQUE (name);
ALTER TABLE ONLY public.payment_methods ADD CONSTRAINT payment_methods_banco_coherente CHECK (((kind = 'BANCO'::payment_method_kind) OR ((bank_name IS NULL) AND (account_number IS NULL) AND (cbu IS NULL))));
ALTER TABLE ONLY public.payment_methods ADD CONSTRAINT payment_methods_cartera_sin_saldo_inicial CHECK (((kind <> 'CARTERA_CHEQUES'::payment_method_kind) OR (opening_balance = (0)::numeric)));
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_payment_order_id_purchase_invoice_key UNIQUE (payment_order_id, purchase_invoice_id);
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_provisional_unica UNIQUE (payment_order_id, provisional_credit_note_id);
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_amount_check CHECK ((amount <> (0)::numeric));
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_uno_de_los_dos CHECK ((((purchase_invoice_id IS NOT NULL) AND (provisional_credit_note_id IS NULL)) OR ((purchase_invoice_id IS NULL) AND (provisional_credit_note_id IS NOT NULL))));
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES payment_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_provisional_credit_note_id_fkey FOREIGN KEY (provisional_credit_note_id) REFERENCES provisional_credit_notes(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_order_allocations ADD CONSTRAINT payment_order_allocations_purchase_invoice_id_fkey FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_order_sequence ADD CONSTRAINT payment_order_sequence_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_order_sequence ADD CONSTRAINT payment_order_sequence_id_check CHECK (id);
ALTER TABLE ONLY public.payment_order_sequence ADD CONSTRAINT payment_order_sequence_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_coherente CHECK ((((kind = 'MEDIO_PAGO'::payment_value_kind) AND (payment_method_id IS NOT NULL) AND (check_id IS NULL) AND (tax_rate_id IS NULL)) OR ((kind = 'CHEQUE_ENDOSADO'::payment_value_kind) AND (check_id IS NOT NULL) AND (payment_method_id IS NULL) AND (tax_rate_id IS NULL)) OR ((kind = 'RETENCION'::payment_value_kind) AND (tax_rate_id IS NOT NULL) AND (payment_method_id IS NULL) AND (check_id IS NULL)) OR ((kind = 'SALDO_A_FAVOR'::payment_value_kind) AND (payment_method_id IS NULL) AND (check_id IS NULL) AND (tax_rate_id IS NULL))));
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_check_id_fkey FOREIGN KEY (check_id) REFERENCES third_party_checks(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES payment_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payment_order_values ADD CONSTRAINT payment_order_values_tax_rate_id_fkey FOREIGN KEY (tax_rate_id) REFERENCES tax_rates(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_number_key UNIQUE (number);
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_anulada_con_motivo CHECK ((((status = 'ANULADA'::payment_order_status) AND (voided_at IS NOT NULL) AND (voided_reason IS NOT NULL)) OR ((status = 'REGISTRADA'::payment_order_status) AND (voided_at IS NULL) AND (voided_reason IS NULL))));
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_applied_amount_check CHECK ((applied_amount >= (0)::numeric));
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_imputado_no_supera_pagado CHECK ((applied_amount <= total_amount));
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_total_amount_check CHECK ((total_amount >= (0)::numeric));
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.payment_orders ADD CONSTRAINT payment_orders_treasury_movement_id_fkey FOREIGN KEY (treasury_movement_id) REFERENCES treasury_movements(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.price_imports ADD CONSTRAINT price_imports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.price_imports ADD CONSTRAINT price_imports_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_position_check CHECK (("position" = ANY (ARRAY['operario'::text, 'administrativo'::text, 'dueño'::text, 'contador'::text])));
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'operario'::text, 'contador'::text])));
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.provisional_credit_note_sequence ADD CONSTRAINT provisional_credit_note_sequence_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.provisional_credit_note_sequence ADD CONSTRAINT provisional_credit_note_sequence_id_check CHECK (id);
ALTER TABLE ONLY public.provisional_credit_note_sequence ADD CONSTRAINT provisional_credit_note_sequence_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_number_key UNIQUE (number);
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_formalizada_con_match CHECK ((((status = 'FORMALIZADA'::provisional_credit_note_status) AND (matched_invoice_id IS NOT NULL) AND (matched_at IS NOT NULL)) OR ((status = 'PENDIENTE'::provisional_credit_note_status) AND (matched_invoice_id IS NULL) AND (matched_at IS NULL))));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_settled_amount_check CHECK ((settled_amount >= (0)::numeric));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_settled_no_supera CHECK ((settled_amount <= amount));
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_matched_invoice_id_fkey FOREIGN KEY (matched_invoice_id) REFERENCES purchase_invoices(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.provisional_credit_notes ADD CONSTRAINT provisional_credit_notes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.purchase_invoice_extractions ADD CONSTRAINT purchase_invoice_extractions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.purchase_invoice_extractions ADD CONSTRAINT purchase_invoice_extractions_kind_check CHECK ((kind = ANY (ARRAY['ARTICULOS'::text, 'CONCEPTOS'::text])));
ALTER TABLE ONLY public.purchase_invoice_extractions ADD CONSTRAINT purchase_invoice_extractions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.purchase_invoice_extractions ADD CONSTRAINT purchase_invoice_extractions_purchase_invoice_id_fkey FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.purchase_invoice_extractions ADD CONSTRAINT purchase_invoice_extractions_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_discount_percent_check CHECK (((discount_percent >= (0)::numeric) AND (discount_percent <= (100)::numeric)));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_net_amount_check CHECK ((net_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_vat_amount_check CHECK ((vat_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_vat_treatment_check CHECK ((vat_treatment = ANY (ARRAY['GRAVADO'::text, 'EXENTO'::text, 'NO_GRAVADO'::text])));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_item_articulo_o_concepto CHECK (((article_id IS NULL) OR (concept_id IS NULL)));
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES expense_concepts(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_purchase_invoice_id_fkey FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.purchase_invoice_items ADD CONSTRAINT purchase_invoice_items_vat_rate_id_fkey FOREIGN KEY (vat_rate_id) REFERENCES tax_rates(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.purchase_invoice_taxes ADD CONSTRAINT purchase_invoice_taxes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.purchase_invoice_taxes ADD CONSTRAINT purchase_invoice_taxes_amount_check CHECK ((amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_taxes ADD CONSTRAINT purchase_invoice_taxes_base_amount_check CHECK ((base_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoice_taxes ADD CONSTRAINT purchase_invoice_taxes_purchase_invoice_id_fkey FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.purchase_invoice_taxes ADD CONSTRAINT purchase_invoice_taxes_tax_rate_id_fkey FOREIGN KEY (tax_rate_id) REFERENCES tax_rates(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_anulada_con_motivo CHECK ((((status = 'ANULADA'::purchase_status) AND (voided_at IS NOT NULL) AND (voided_reason IS NOT NULL)) OR ((status = 'REGISTRADA'::purchase_status) AND (voided_at IS NULL) AND (voided_reason IS NULL))));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_general_discount_amount_check CHECK ((general_discount_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_general_discount_percent_check CHECK (((general_discount_percent >= (0)::numeric) AND (general_discount_percent <= (100)::numeric)));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_gross_amount_check CHECK ((gross_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_line_discount_amount_check CHECK ((line_discount_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_net_exempt_check CHECK ((net_exempt >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_net_taxed_check CHECK ((net_taxed >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_net_untaxed_check CHECK ((net_untaxed >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_other_taxes_amount_check CHECK ((other_taxes_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_payment_terms_days_check CHECK ((payment_terms_days >= 0));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_sales_point_check CHECK (((sales_point >= 0) AND (sales_point <= 99999)));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_settled_amount_check CHECK ((settled_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_total_amount_check CHECK ((total_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_vat_amount_check CHECK ((vat_amount >= (0)::numeric));
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.purchase_invoices ADD CONSTRAINT purchase_invoices_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_number_key UNIQUE (number);
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id);
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_allocations ADD CONSTRAINT receipt_allocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_allocations ADD CONSTRAINT receipt_allocations_receipt_id_invoice_id_key UNIQUE (receipt_id, invoice_id);
ALTER TABLE ONLY public.receipt_allocations ADD CONSTRAINT receipt_allocations_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.receipt_allocations ADD CONSTRAINT receipt_allocations_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_allocations ADD CONSTRAINT receipt_allocations_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_coherente CHECK ((((kind = 'MEDIO_PAGO'::receipt_change_kind) AND (payment_method_id IS NOT NULL) AND (treasury_movement_id IS NOT NULL) AND (note IS NULL) AND (check_id IS NULL)) OR ((kind = 'CHEQUE_PROPIO'::receipt_change_kind) AND (payment_method_id IS NULL) AND (treasury_movement_id IS NULL) AND (note IS NOT NULL) AND (check_id IS NULL)) OR ((kind = 'CHEQUE_ENDOSADO'::receipt_change_kind) AND (payment_method_id IS NULL) AND (treasury_movement_id IS NOT NULL) AND (note IS NULL) AND (check_id IS NOT NULL))));
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_check_id_fkey FOREIGN KEY (check_id) REFERENCES third_party_checks(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.receipt_changes ADD CONSTRAINT receipt_changes_treasury_movement_id_fkey FOREIGN KEY (treasury_movement_id) REFERENCES treasury_movements(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_sequence ADD CONSTRAINT receipt_sequence_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_sequence ADD CONSTRAINT receipt_sequence_id_check CHECK (id);
ALTER TABLE ONLY public.receipt_sequence ADD CONSTRAINT receipt_sequence_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_coherente CHECK ((((kind = 'MEDIO_PAGO'::receipt_value_kind) AND (payment_method_id IS NOT NULL) AND (check_id IS NULL) AND (tax_rate_id IS NULL)) OR ((kind = 'CHEQUE'::receipt_value_kind) AND (check_id IS NOT NULL) AND (payment_method_id IS NULL) AND (tax_rate_id IS NULL)) OR ((kind = 'RETENCION'::receipt_value_kind) AND (tax_rate_id IS NOT NULL) AND (payment_method_id IS NULL) AND (check_id IS NULL)) OR ((kind = 'SALDO_A_FAVOR'::receipt_value_kind) AND (payment_method_id IS NULL) AND (check_id IS NULL) AND (tax_rate_id IS NULL))));
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_check_id_fkey FOREIGN KEY (check_id) REFERENCES third_party_checks(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.receipt_values ADD CONSTRAINT receipt_values_tax_rate_id_fkey FOREIGN KEY (tax_rate_id) REFERENCES tax_rates(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_number_key UNIQUE (number);
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_anulado_con_motivo CHECK ((((status = 'ANULADO'::receipt_status) AND (voided_at IS NOT NULL) AND (voided_reason IS NOT NULL)) OR ((status = 'REGISTRADO'::receipt_status) AND (voided_at IS NULL) AND (voided_reason IS NULL))));
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_applied_amount_check CHECK ((applied_amount >= (0)::numeric));
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_imputado_no_supera_cobrado CHECK ((applied_amount <= total_amount));
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_total_amount_check CHECK ((total_amount > (0)::numeric));
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.receipts ADD CONSTRAINT receipts_treasury_movement_id_fkey FOREIGN KEY (treasury_movement_id) REFERENCES treasury_movements(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.remito_items ADD CONSTRAINT remito_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.remito_items ADD CONSTRAINT remito_items_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id);
ALTER TABLE ONLY public.remito_items ADD CONSTRAINT remito_items_remito_id_fkey FOREIGN KEY (remito_id) REFERENCES remitos(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.remito_sequences ADD CONSTRAINT remito_sequences_pkey PRIMARY KEY (sales_point);
ALTER TABLE ONLY public.remitos ADD CONSTRAINT remitos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.remitos ADD CONSTRAINT remitos_sales_point_number_key UNIQUE (sales_point, number);
ALTER TABLE ONLY public.remitos ADD CONSTRAINT remitos_status_check CHECK ((status = ANY (ARRAY['EMITIDO'::text, 'ANULADO'::text])));
ALTER TABLE ONLY public.remitos ADD CONSTRAINT remitos_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE ONLY public.remitos ADD CONSTRAINT remitos_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id);
ALTER TABLE ONLY public.supplier_import_profiles ADD CONSTRAINT supplier_import_profiles_pkey PRIMARY KEY (supplier_id);
ALTER TABLE ONLY public.supplier_import_profiles ADD CONSTRAINT supplier_import_profiles_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_code_prefix_key UNIQUE (code_prefix);
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_code_prefix_length CHECK (((code_prefix IS NULL) OR (length(code_prefix) = 2)));
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_payment_terms_days_check CHECK (((payment_terms_days >= 0) AND (payment_terms_days <= 365)));
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_tax_condition_check CHECK ((tax_condition = ANY (ARRAY['RESPONSABLE_INSCRIPTO'::text, 'MONOTRIBUTO'::text, 'EXENTO'::text, 'CONSUMIDOR_FINAL'::text])));
ALTER TABLE ONLY public.tax_rates ADD CONSTRAINT tax_rates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_rates ADD CONSTRAINT tax_rates_kind_name_key UNIQUE (kind, name);
ALTER TABLE ONLY public.tax_rates ADD CONSTRAINT tax_rates_iva_coherente CHECK ((((kind = 'IVA'::tax_kind) AND (vat_treatment IS NOT NULL) AND (base = 'NETO'::tax_base)) OR ((kind <> 'IVA'::tax_kind) AND (vat_treatment IS NULL))));
ALTER TABLE ONLY public.tax_rates ADD CONSTRAINT tax_rates_rate_check CHECK (((rate >= (0)::numeric) AND (rate <= (100)::numeric)));
ALTER TABLE ONLY public.tax_rates ADD CONSTRAINT tax_rates_vat_treatment_check CHECK ((vat_treatment = ANY (ARRAY['GRAVADO'::text, 'EXENTO'::text, 'NO_GRAVADO'::text])));
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_deposited_to_id_fkey FOREIGN KEY (deposited_to_id) REFERENCES payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_endorsed_to_customer_id_fkey FOREIGN KEY (endorsed_to_customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_endorsed_to_supplier_id_fkey FOREIGN KEY (endorsed_to_supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.third_party_checks ADD CONSTRAINT third_party_checks_received_movement_id_fkey FOREIGN KEY (received_movement_id) REFERENCES treasury_movements(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.treasury_movement_legs ADD CONSTRAINT treasury_movement_legs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.treasury_movement_legs ADD CONSTRAINT treasury_movement_legs_amount_check CHECK ((amount <> (0)::numeric));
ALTER TABLE ONLY public.treasury_movement_legs ADD CONSTRAINT treasury_movement_legs_movement_id_fkey FOREIGN KEY (movement_id) REFERENCES treasury_movements(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.treasury_movement_legs ADD CONSTRAINT treasury_movement_legs_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_movement_type_number_key UNIQUE (movement_type, number);
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_anulado_con_motivo CHECK ((((status = 'ANULADO'::treasury_status) AND (voided_at IS NOT NULL) AND (voided_reason IS NOT NULL)) OR ((status = 'REGISTRADO'::treasury_status) AND (voided_at IS NULL) AND (voided_reason IS NULL))));
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_number_check CHECK ((number > 0));
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES expense_concepts(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.treasury_movements ADD CONSTRAINT treasury_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.treasury_sequences ADD CONSTRAINT treasury_sequences_pkey PRIMARY KEY (movement_type);
ALTER TABLE ONLY public.treasury_sequences ADD CONSTRAINT treasury_sequences_last_number_check CHECK ((last_number >= 0));
ALTER TABLE ONLY public.vehicle_brands ADD CONSTRAINT vehicle_brands_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_intake_parts ADD CONSTRAINT vehicle_intake_parts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_intake_parts ADD CONSTRAINT vehicle_intake_parts_intake_id_fkey FOREIGN KEY (intake_id) REFERENCES vehicle_intakes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vehicle_intake_photos ADD CONSTRAINT vehicle_intake_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_intake_photos ADD CONSTRAINT vehicle_intake_photos_intake_id_fkey FOREIGN KEY (intake_id) REFERENCES vehicle_intakes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vehicle_intakes ADD CONSTRAINT vehicle_intakes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_intakes ADD CONSTRAINT vehicle_intakes_number_key UNIQUE (number);
ALTER TABLE ONLY public.vehicle_intakes ADD CONSTRAINT vehicle_intakes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE ONLY public.vehicle_intakes ADD CONSTRAINT vehicle_intakes_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.vehicle_intakes ADD CONSTRAINT vehicle_intakes_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id);
ALTER TABLE ONLY public.vehicle_models ADD CONSTRAINT vehicle_models_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_models ADD CONSTRAINT vehicle_models_size_class_check CHECK ((size_class = ANY (ARRAY['MEDIANO'::text, 'GRANDE'::text])));
ALTER TABLE ONLY public.vehicle_models ADD CONSTRAINT vehicle_models_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES vehicle_brands(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vehicle_part_types ADD CONSTRAINT vehicle_part_types_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_parts ADD CONSTRAINT vehicle_parts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_parts ADD CONSTRAINT vehicle_parts_quantity_check CHECK ((quantity > 0));
ALTER TABLE ONLY public.vehicle_parts ADD CONSTRAINT vehicle_parts_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vehicle_photos ADD CONSTRAINT vehicle_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicle_photos ADD CONSTRAINT vehicle_photos_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_injector_count_check CHECK (((injector_count IS NULL) OR (injector_count >= 0)));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_kind_check CHECK ((kind = ANY (ARRAY['VEHICULO'::text, 'PIEZA'::text])));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_odometer_check CHECK (((odometer IS NULL) OR (odometer >= (0)::numeric)));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_odometer_unit_check CHECK ((odometer_unit = ANY (ARRAY['KM'::text, 'HORAS'::text])));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_size_class_check CHECK ((size_class = ANY (ARRAY['MEDIANO'::text, 'GRANDE'::text])));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_vehicle_type_check CHECK ((vehicle_type = ANY (ARRAY['CAMION'::text, 'MAQUINARIA'::text, 'GENERADOR'::text, 'EMBARCACION'::text, 'AGRICOLA'::text, 'OTRO'::text])));
ALTER TABLE ONLY public.vehicles ADD CONSTRAINT vehicles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_items ADD CONSTRAINT work_order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_order_items ADD CONSTRAINT work_order_items_article_id_fkey FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.work_order_items ADD CONSTRAINT work_order_items_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_photos ADD CONSTRAINT work_order_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_order_photos ADD CONSTRAINT work_order_photos_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_received_parts ADD CONSTRAINT work_order_received_parts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_order_received_parts ADD CONSTRAINT work_order_received_parts_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_stage_assignments ADD CONSTRAINT work_order_stage_assignments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_order_stage_assignments ADD CONSTRAINT work_order_stage_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.work_order_stage_assignments ADD CONSTRAINT work_order_stage_assignments_status_id_fkey FOREIGN KEY (status_id) REFERENCES work_order_statuses(id);
ALTER TABLE ONLY public.work_order_stage_assignments ADD CONSTRAINT work_order_stage_assignments_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_status_history ADD CONSTRAINT work_order_status_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_order_status_history ADD CONSTRAINT work_order_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.work_order_status_history ADD CONSTRAINT work_order_status_history_from_status_id_fkey FOREIGN KEY (from_status_id) REFERENCES work_order_statuses(id);
ALTER TABLE ONLY public.work_order_status_history ADD CONSTRAINT work_order_status_history_to_status_id_fkey FOREIGN KEY (to_status_id) REFERENCES work_order_statuses(id);
ALTER TABLE ONLY public.work_order_status_history ADD CONSTRAINT work_order_status_history_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.work_order_statuses ADD CONSTRAINT work_order_statuses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_number_key UNIQUE (number);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_price_auth_status_check CHECK (((price_auth_status IS NULL) OR (price_auth_status = ANY (ARRAY['PENDIENTE'::text, 'AUTORIZADO'::text, 'RECHAZADO'::text]))));
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_reception_kind_check CHECK ((reception_kind = ANY (ARRAY['VEHICULO'::text, 'PIEZA'::text])));
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_status_id_fkey FOREIGN KEY (status_id) REFERENCES work_order_statuses(id);
ALTER TABLE ONLY public.work_orders ADD CONSTRAINT work_orders_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id);
ALTER TABLE ONLY public.workplace_capacity ADD CONSTRAINT workplace_capacity_pkey PRIMARY KEY (workplace);
ALTER TABLE ONLY public.yard_reservations ADD CONSTRAINT yard_reservations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.yard_reservations ADD CONSTRAINT yard_reservations_rango_valido CHECK ((ends_on >= starts_on));
ALTER TABLE ONLY public.yard_reservations ADD CONSTRAINT yard_reservations_size_class_check CHECK ((size_class = ANY (ARRAY['MEDIANO'::text, 'GRANDE'::text])));
ALTER TABLE ONLY public.yard_reservations ADD CONSTRAINT yard_reservations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
ALTER TABLE ONLY public.yard_reservations ADD CONSTRAINT yard_reservations_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
