CREATE SEQUENCE public.quotation_number_seq START WITH 1000 INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE public.vehicle_intake_number_seq START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE public.work_order_number_seq START WITH 5000 INCREMENT BY 1 MINVALUE 1;
