CREATE INDEX article_components_combo_idx ON public.article_components USING btree (combo_article_id, "position");
CREATE INDEX article_suppliers_article_idx ON public.article_suppliers USING btree (article_id);
CREATE UNIQUE INDEX article_suppliers_one_preferred ON public.article_suppliers USING btree (article_id) WHERE is_preferred;
CREATE UNIQUE INDEX article_suppliers_supplier_code_key ON public.article_suppliers USING btree (supplier_id, upper(supplier_code));
CREATE INDEX customers_name_idx ON public.customers USING btree (lower(name));
CREATE UNIQUE INDEX customers_tax_id_key ON public.customers USING btree (tax_id) WHERE (tax_id IS NOT NULL);
CREATE INDEX invoice_items_invoice_idx ON public.invoice_items USING btree (invoice_id, line_number);
CREATE INDEX invoices_customer_idx ON public.invoices USING btree (customer_id);
CREATE INDEX invoices_due_date_idx ON public.invoices USING btree (due_date);
CREATE INDEX invoices_status_idx ON public.invoices USING btree (status);
CREATE UNIQUE INDEX invoices_una_activa_por_ot ON public.invoices USING btree (work_order_id) WHERE (status = 'EMITIDA'::invoice_status);
CREATE INDEX notifications_pendientes_idx ON public.notifications USING btree (created_at) WHERE (status = 'PENDIENTE'::notification_status);
CREATE INDEX notifications_quotation_idx ON public.notifications USING btree (quotation_id);
CREATE INDEX notifications_receipt_value_idx ON public.notifications USING btree (receipt_value_id);
CREATE INDEX notifications_work_order_idx ON public.notifications USING btree (work_order_id);
CREATE INDEX payment_methods_kind_idx ON public.payment_methods USING btree (kind) WHERE active;
CREATE UNIQUE INDEX payment_methods_una_cartera ON public.payment_methods USING btree (kind) WHERE (kind = 'CARTERA_CHEQUES'::payment_method_kind);
CREATE INDEX payment_order_allocations_doc_idx ON public.payment_order_allocations USING btree (purchase_invoice_id);
CREATE INDEX payment_order_allocations_provisional_idx ON public.payment_order_allocations USING btree (provisional_credit_note_id);
CREATE INDEX payment_order_values_order_idx ON public.payment_order_values USING btree (payment_order_id);
CREATE INDEX payment_orders_date_idx ON public.payment_orders USING btree (payment_date DESC);
CREATE INDEX payment_orders_supplier_idx ON public.payment_orders USING btree (supplier_id);
CREATE INDEX price_imports_supplier_idx ON public.price_imports USING btree (supplier_id, imported_at DESC);
CREATE INDEX provisional_credit_notes_supplier_idx ON public.provisional_credit_notes USING btree (supplier_id);
CREATE INDEX purchase_invoice_extractions_status_idx ON public.purchase_invoice_extractions USING btree (status) WHERE (status = 'EXTRAIDO'::purchase_extraction_status);
CREATE INDEX purchase_invoice_items_idx ON public.purchase_invoice_items USING btree (purchase_invoice_id, line_number);
CREATE INDEX purchase_invoice_taxes_idx ON public.purchase_invoice_taxes USING btree (purchase_invoice_id);
CREATE INDEX purchase_invoices_due_date_idx ON public.purchase_invoices USING btree (due_date);
CREATE INDEX purchase_invoices_issue_date_idx ON public.purchase_invoices USING btree (issue_date);
CREATE UNIQUE INDEX purchase_invoices_sin_duplicados ON public.purchase_invoices USING btree (supplier_id, doc_type, letter, sales_point, number) WHERE (status = 'REGISTRADA'::purchase_status);
CREATE INDEX purchase_invoices_supplier_idx ON public.purchase_invoices USING btree (supplier_id);
CREATE INDEX quotation_items_quotation_idx ON public.quotation_items USING btree (quotation_id);
CREATE UNIQUE INDEX quotations_public_token_key ON public.quotations USING btree (public_token);
CREATE INDEX quotations_status_idx ON public.quotations USING btree (status);
CREATE INDEX receipt_allocations_invoice_idx ON public.receipt_allocations USING btree (invoice_id);
CREATE INDEX receipt_changes_receipt_id_idx ON public.receipt_changes USING btree (receipt_id);
CREATE INDEX receipt_values_receipt_idx ON public.receipt_values USING btree (receipt_id);
CREATE INDEX receipts_customer_idx ON public.receipts USING btree (customer_id);
CREATE INDEX receipts_date_idx ON public.receipts USING btree (receipt_date DESC);
CREATE INDEX suppliers_name_idx ON public.suppliers USING btree (lower(name));
CREATE UNIQUE INDEX suppliers_tax_id_key ON public.suppliers USING btree (tax_id) WHERE (tax_id IS NOT NULL);
CREATE INDEX tax_rates_kind_idx ON public.tax_rates USING btree (kind) WHERE active;
CREATE INDEX third_party_checks_due_idx ON public.third_party_checks USING btree (due_date);
CREATE UNIQUE INDEX third_party_checks_sin_duplicados ON public.third_party_checks USING btree (upper(bank_name), number);
CREATE INDEX third_party_checks_status_idx ON public.third_party_checks USING btree (status);
CREATE INDEX treasury_legs_method_idx ON public.treasury_movement_legs USING btree (payment_method_id);
CREATE INDEX treasury_legs_movement_idx ON public.treasury_movement_legs USING btree (movement_id);
CREATE INDEX treasury_movements_concept_idx ON public.treasury_movements USING btree (concept_id);
CREATE INDEX treasury_movements_date_idx ON public.treasury_movements USING btree (movement_date DESC);
CREATE UNIQUE INDEX vehicle_brands_name_idx ON public.vehicle_brands USING btree (lower(name));
CREATE INDEX vehicle_intake_parts_intake_id_idx ON public.vehicle_intake_parts USING btree (intake_id);
CREATE UNIQUE INDEX vehicle_models_brand_name_idx ON public.vehicle_models USING btree (brand_id, lower(name));
CREATE UNIQUE INDEX vehicle_part_types_name_idx ON public.vehicle_part_types USING btree (lower(name));
CREATE INDEX vehicle_parts_vehicle_idx ON public.vehicle_parts USING btree (vehicle_id, "position");
CREATE INDEX vehicle_photos_vehicle_id_idx ON public.vehicle_photos USING btree (vehicle_id);
CREATE INDEX vehicles_customer_idx ON public.vehicles USING btree (customer_id);
CREATE INDEX vehicles_kind_idx ON public.vehicles USING btree (kind);
CREATE UNIQUE INDEX vehicles_license_plate_key ON public.vehicles USING btree (upper(license_plate)) WHERE (license_plate IS NOT NULL);
CREATE UNIQUE INDEX vehicles_vin_key ON public.vehicles USING btree (upper(vin)) WHERE (vin IS NOT NULL);
CREATE INDEX work_order_photos_work_order_id_idx ON public.work_order_photos USING btree (work_order_id);
CREATE INDEX work_order_received_parts_wo_idx ON public.work_order_received_parts USING btree (work_order_id);
CREATE INDEX work_order_stage_assignments_open_idx ON public.work_order_stage_assignments USING btree (work_order_id) WHERE (ended_at IS NULL);
CREATE INDEX work_order_stage_assignments_status_id_idx ON public.work_order_stage_assignments USING btree (status_id);
CREATE INDEX work_order_stage_assignments_work_order_id_idx ON public.work_order_stage_assignments USING btree (work_order_id);
CREATE INDEX wo_status_history_order_idx ON public.work_order_status_history USING btree (work_order_id, changed_at);
CREATE UNIQUE INDEX work_order_statuses_one_initial ON public.work_order_statuses USING btree (is_initial) WHERE is_initial;
CREATE UNIQUE INDEX work_order_statuses_system_key_idx ON public.work_order_statuses USING btree (system_key) WHERE (system_key IS NOT NULL);
CREATE UNIQUE INDEX work_orders_public_token_key ON public.work_orders USING btree (public_token);
CREATE INDEX yard_reservations_rango_idx ON public.yard_reservations USING btree (starts_on, ends_on);
