CREATE TRIGGER article_components_un_solo_nivel BEFORE INSERT OR UPDATE ON public.article_components FOR EACH ROW EXECUTE FUNCTION article_components_un_solo_nivel();
CREATE TRIGGER article_suppliers_recalc_price AFTER INSERT OR DELETE OR UPDATE OF purchase_price, is_preferred ON public.article_suppliers FOR EACH ROW EXECUTE FUNCTION article_suppliers_recalc();
CREATE TRIGGER article_suppliers_set_updated_at BEFORE UPDATE ON public.article_suppliers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER articles_markup_recalc BEFORE UPDATE ON public.articles FOR EACH ROW EXECUTE FUNCTION articles_recalc_on_markup();
CREATE TRIGGER articles_price_updated_at BEFORE UPDATE ON public.articles FOR EACH ROW EXECUTE FUNCTION articles_track_price_change();
CREATE TRIGGER company_settings_set_updated_at BEFORE UPDATE ON public.company_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER customers_sync_phone BEFORE INSERT OR UPDATE OF phone ON public.customers FOR EACH ROW EXECUTE FUNCTION sync_customer_phone();
CREATE TRIGGER invoices_set_updated_at BEFORE UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER payment_methods_set_updated_at BEFORE UPDATE ON public.payment_methods FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER payment_orders_set_updated_at BEFORE UPDATE ON public.payment_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER purchase_invoices_set_updated_at BEFORE UPDATE ON public.purchase_invoices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER quotations_set_updated_at BEFORE UPDATE ON public.quotations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER receipts_set_updated_at BEFORE UPDATE ON public.receipts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER suppliers_normalize_code_prefix BEFORE INSERT OR UPDATE OF code_prefix ON public.suppliers FOR EACH ROW EXECUTE FUNCTION normalize_supplier_code_prefix();
CREATE TRIGGER third_party_checks_set_updated_at BEFORE UPDATE ON public.third_party_checks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER treasury_movements_set_updated_at BEFORE UPDATE ON public.treasury_movements FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER vehicle_intakes_set_updated_at BEFORE UPDATE ON public.vehicle_intakes FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER work_order_items_stock AFTER INSERT OR DELETE OR UPDATE ON public.work_order_items FOR EACH ROW EXECUTE FUNCTION work_order_items_stock_sync();
CREATE TRIGGER work_order_statuses_set_updated_at BEFORE UPDATE ON public.work_order_statuses FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER work_orders_block_terminal_while_price_pending BEFORE UPDATE OF status_id ON public.work_orders FOR EACH ROW EXECUTE FUNCTION block_terminal_while_price_pending();
CREATE TRIGGER work_orders_enqueue_created AFTER INSERT ON public.work_orders FOR EACH ROW EXECUTE FUNCTION enqueue_work_order_created();
CREATE TRIGGER work_orders_enqueue_status AFTER UPDATE OF status_id ON public.work_orders FOR EACH ROW EXECUTE FUNCTION enqueue_work_order_status();
CREATE TRIGGER work_orders_log_stage_assignment AFTER INSERT OR UPDATE OF employee_id, status_id ON public.work_orders FOR EACH ROW EXECUTE FUNCTION log_work_order_stage_assignment();
CREATE TRIGGER work_orders_log_status AFTER INSERT OR UPDATE OF status_id ON public.work_orders FOR EACH ROW EXECUTE FUNCTION log_work_order_status_change();
CREATE TRIGGER work_orders_set_updated_at BEFORE UPDATE ON public.work_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER workplace_capacity_set_updated_at BEFORE UPDATE ON public.workplace_capacity FOR EACH ROW EXECUTE FUNCTION set_updated_at();
