-- ── Activar RLS en cada tabla ──────────────────────────────────────────────
-- NOTA DE SEGURIDAD: en la base original, remito_sequences tiene RLS
-- DESACTIVADO (bug conocido, no corregido a propósito para esta clonación:
-- ver el aviso al final de este documento). Se replica tal cual está hoy.
-- Si querés partir ya corregido en el proyecto nuevo, agregá:
--   ALTER TABLE public.remito_sequences ENABLE ROW LEVEL SECURITY;
-- (con RLS activado y sin políticas, esa tabla queda ilegible incluso para
-- admin hasta que se le agregue una policy explícita).
ALTER TABLE public.ai_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arca_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arca_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_code_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_order_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_order_sequence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_order_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provisional_credit_note_sequence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provisional_credit_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_invoice_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_invoice_taxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_sequence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipt_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.remito_items ENABLE ROW LEVEL SECURITY;
-- remito_sequences: sin ENABLE a propósito, ver nota de seguridad arriba.
ALTER TABLE public.remitos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_import_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.third_party_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treasury_movement_legs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treasury_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treasury_sequences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_intake_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_intake_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_intakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_part_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicle_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_received_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_stage_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_order_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workplace_capacity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yard_reservations ENABLE ROW LEVEL SECURITY;

-- ── Políticas ───────────────────────────────────────────────────────────────
CREATE POLICY "admin insert" ON public.app_settings AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.app_settings AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.app_settings AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.article_code_sequences AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin actualiza" ON public.article_components AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin());
CREATE POLICY "admin borra" ON public.article_components AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin());
CREATE POLICY "admin escribe" ON public.article_components AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.article_components AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin delete" ON public.article_suppliers AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.article_suppliers AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.article_suppliers AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.article_suppliers AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.articles AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.articles AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.articles AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.articles AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.banks AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.banks AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.banks AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.banks AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "admin update" ON public.company_settings AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.company_settings AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.customers AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.customers AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.customers AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "lectura segun rol" ON public.customers AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin() OR (EXISTS ( SELECT 1
   FROM work_orders w
  WHERE ((w.customer_id = customers.id) AND (w.employee_id = current_employee_id()))))));
CREATE POLICY "admin delete" ON public.employees AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.employees AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.employees AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "authenticated read" ON public.employees AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin delete" ON public.expense_concepts AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.expense_concepts AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.expense_concepts AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.expense_concepts AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.invoice_items AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.invoice_sequences AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.invoices AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.invoices AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin update" ON public.notification_templates AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.notification_templates AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.notifications AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.payment_methods AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.payment_methods AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.payment_methods AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.payment_methods AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.payment_order_allocations AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.payment_order_sequence AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.payment_order_values AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.payment_order_values AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.payment_orders AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.payment_orders AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.price_imports AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.price_imports AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.price_imports AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin read all profiles" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "users read own profile" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id));
CREATE POLICY "solo admin" ON public.provisional_credit_note_sequence AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.provisional_credit_notes AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.purchase_invoice_extractions AS PERMISSIVE FOR DELETE TO public USING ((is_admin() AND (status <> 'CONFIRMADO'::purchase_extraction_status)));
CREATE POLICY "admin insert" ON public.purchase_invoice_extractions AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin select" ON public.purchase_invoice_extractions AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "admin update" ON public.purchase_invoice_extractions AS PERMISSIVE FOR UPDATE TO public USING (is_admin());
CREATE POLICY "solo admin" ON public.purchase_invoice_items AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.purchase_invoice_taxes AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.purchase_invoices AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.purchase_invoices AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.quotation_items AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.quotation_items AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.quotation_items AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.quotation_items AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.quotations AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.quotations AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.quotations AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.quotations AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.receipt_allocations AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.receipt_changes AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.receipt_sequence AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.receipt_values AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.receipt_values AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "contador lee" ON public.receipts AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.receipts AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.remito_items AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "solo admin" ON public.remitos AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "admin delete" ON public.supplier_import_profiles AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin());
CREATE POLICY "admin insert" ON public.supplier_import_profiles AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "admin select" ON public.supplier_import_profiles AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin update" ON public.supplier_import_profiles AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "admin delete" ON public.suppliers AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.suppliers AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.suppliers AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "contador lee" ON public.suppliers AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.suppliers AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin delete" ON public.tax_rates AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.tax_rates AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.tax_rates AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "contador lee" ON public.tax_rates AS PERMISSIVE FOR SELECT TO public USING (is_contador());
CREATE POLICY "solo admin" ON public.tax_rates AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.third_party_checks AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.treasury_movement_legs AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.treasury_movements AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "solo admin" ON public.treasury_sequences AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "admin actualiza" ON public.vehicle_brands AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin());
CREATE POLICY "admin escribe" ON public.vehicle_brands AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.vehicle_brands AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin delete" ON public.vehicle_intake_parts AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.vehicle_intake_parts AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.vehicle_intake_parts AS PERMISSIVE FOR UPDATE TO public USING (is_admin());
CREATE POLICY "read all" ON public.vehicle_intake_parts AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "admin delete" ON public.vehicle_intake_photos AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.vehicle_intake_photos AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "read all" ON public.vehicle_intake_photos AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "admin delete" ON public.vehicle_intakes AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.vehicle_intakes AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.vehicle_intakes AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "read all" ON public.vehicle_intakes AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "admin actualiza" ON public.vehicle_models AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin());
CREATE POLICY "admin escribe" ON public.vehicle_models AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.vehicle_models AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin actualiza" ON public.vehicle_part_types AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin());
CREATE POLICY "admin escribe" ON public.vehicle_part_types AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.vehicle_part_types AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin actualiza" ON public.vehicle_parts AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin());
CREATE POLICY "admin borra" ON public.vehicle_parts AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin());
CREATE POLICY "admin escribe" ON public.vehicle_parts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.vehicle_parts AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin delete" ON public.vehicle_photos AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.vehicle_photos AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.vehicle_photos AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin delete" ON public.vehicles AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.vehicles AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.vehicles AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "lectura segun rol" ON public.vehicles AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin() OR (EXISTS ( SELECT 1
   FROM work_orders w
  WHERE ((w.vehicle_id = vehicles.id) AND (w.employee_id = current_employee_id()))))));
CREATE POLICY "admin delete" ON public.work_order_items AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.work_order_items AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.work_order_items AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "lectura segun rol" ON public.work_order_items AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin() OR (EXISTS ( SELECT 1
   FROM work_orders w
  WHERE ((w.id = work_order_items.work_order_id) AND (w.employee_id = current_employee_id()))))));
CREATE POLICY "admin delete" ON public.work_order_photos AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.work_order_photos AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "lectura segun rol" ON public.work_order_photos AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM work_orders wo
  WHERE ((wo.id = work_order_photos.work_order_id) AND (is_admin() OR (wo.employee_id = current_employee_id()))))));
CREATE POLICY "admin delete" ON public.work_order_received_parts AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin());
CREATE POLICY "admin insert" ON public.work_order_received_parts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.work_order_received_parts AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "lectura autenticada" ON public.work_order_received_parts AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "lectura segun rol" ON public.work_order_stage_assignments AS PERMISSIVE FOR SELECT TO public USING ((is_admin() OR (EXISTS ( SELECT 1
   FROM work_orders w
  WHERE ((w.id = work_order_stage_assignments.work_order_id) AND (w.employee_id = current_employee_id()))))));
CREATE POLICY "lectura segun rol" ON public.work_order_status_history AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin() OR (EXISTS ( SELECT 1
   FROM work_orders w
  WHERE ((w.id = work_order_status_history.work_order_id) AND (w.employee_id = current_employee_id()))))));
CREATE POLICY "admin delete" ON public.work_order_statuses AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.work_order_statuses AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.work_order_statuses AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "read all" ON public.work_order_statuses AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "admin delete" ON public.work_orders AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.work_orders AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.work_orders AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "lectura segun rol" ON public.work_orders AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin() OR (employee_id = current_employee_id())));
CREATE POLICY "admin insert" ON public.workplace_capacity AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.workplace_capacity AS PERMISSIVE FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "solo admin" ON public.workplace_capacity AS PERMISSIVE FOR SELECT TO public USING (is_admin());
CREATE POLICY "admin delete" ON public.yard_reservations AS PERMISSIVE FOR DELETE TO public USING (is_admin());
CREATE POLICY "admin insert" ON public.yard_reservations AS PERMISSIVE FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY "admin update" ON public.yard_reservations AS PERMISSIVE FOR UPDATE TO public USING (is_admin());
CREATE POLICY "solo admin" ON public.yard_reservations AS PERMISSIVE FOR SELECT TO public USING (is_admin());
