-- Permisos de ejecución por función y por rol. No es el default de Postgres
-- (que da EXECUTE a PUBLIC al crear la función): varias funciones excluyen a
-- propósito a "anon" o incluso a "authenticated" — las que mueven plata o
-- comprobantes (save_receipt, void_invoice, post_treasury_movement, etc.) o
-- las que solo debe llamar el propio servidor (mark_notification_sent,
-- despachar_whatsapp, read_gmail_credential). Se replica tal cual.

REVOKE ALL ON public.ai_credentials FROM anon, authenticated;
REVOKE ALL ON public.arca_credentials FROM anon, authenticated;
REVOKE ALL ON public.arca_tickets FROM anon, authenticated;

GRANT EXECUTE ON FUNCTION public._create_invoice(p_work_order_id uuid, p_customer_id uuid, p_items jsonb, p_notes text, p_emit_remito boolean, p_link_remito_id uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.adjust_article_stock(p_article_id uuid, p_delta numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.aplicar_cotizacion_en_ot(p_quotation_id uuid) TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_quotation_to_work_order(p_quotation_id uuid) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.article_components_un_solo_nivel() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.article_suppliers_recalc() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.articles_recalc_on_markup() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.articles_track_price_change() TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.block_terminal_while_price_pending() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.borrar_certificado_arca(p_proposito text) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.borrar_clave_ia(p_provider text) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.build_work_order_message(p_work_order_id uuid, p_status_id uuid, p_include_intro boolean) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.checks_wallet_id() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_pending_notifications(p_limit integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_pending_retention(p_receipt_value_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.compute_sale_price(p_article_id uuid, p_markup numeric) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cotizacion_sigue_decidible(p_work_order_id uuid) TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.cotizar_desde_ot(p_work_order_id uuid, p_valid_until date) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.create_remito(p_customer_id uuid, p_items jsonb, p_notes text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.credit_check(p_check_id uuid, p_date date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.current_employee_id() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.customer_credit(p_customer_id uuid) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.decide_price_authorization(p_token uuid, p_accept boolean, p_reason text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.decide_quotation(p_token uuid, p_accept boolean, p_reason text) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.delete_work_orders(p_ids uuid[]) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.deposit_check(p_check_id uuid, p_bank_method_id uuid, p_date date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.despachar_whatsapp() TO service_role;
GRANT EXECUTE ON FUNCTION public.diagnosticar_whatsapp() TO service_role;
GRANT EXECUTE ON FUNCTION public.duplicate_quotation(p_quotation_id uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.effective_markup(p_markup numeric) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.endorse_check(p_check_id uuid, p_supplier_id uuid, p_date date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_notification(p_kind notification_kind, p_dedupe_key text, p_body text, p_customer_id uuid, p_work_order_id uuid, p_quotation_id uuid, p_media_url text, p_receipt_value_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_work_order_created() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_work_order_status() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.enviar_cotizacion_para_autorizar(p_quotation_id uuid) TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.estado_certificados_arca() TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.estado_claves_ia() TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_quotation(p_token uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_quotation_items(p_token uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_status_history(p_token uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_work_order(p_token uuid) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.guardar_certificado_arca(p_proposito text, p_cuit text, p_cert text, p_key text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.guardar_clave_ia(p_provider text, p_api_key text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.has_gmail_credential() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.import_supplier_prices(p_supplier_id uuid, p_file_name text, p_rows jsonb) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.invoice_type_for(p_issuer_condition text, p_customer_condition text) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.is_contador() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.issue_free_invoice(p_customer_id uuid, p_items jsonb, p_notes text, p_emit_remito boolean, p_remito_id uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.issue_invoice(p_work_order_id uuid, p_items jsonb, p_notes text, p_emit_remito boolean) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.link_or_create_supplier_article(p_supplier_id uuid, p_supplier_code text, p_description text, p_purchase_price numeric, p_article_id uuid) TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.link_quotation_to_work_order(p_quotation_id uuid, p_work_order_id uuid) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.log_work_order_stage_assignment() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.log_work_order_status_change() TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.mark_notification_failed(p_id uuid, p_error text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_notification_sent(p_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_password_changed() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.match_provisional_credit_note(p_provisional_id uuid, p_invoice_id uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mover_stock_de_renglon(p_article_id uuid, p_delta numeric) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.normalize_ar_phone(p_raw text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.normalize_supplier_code_prefix() TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ordenar_estados_ot(p_ids uuid[]) TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.post_treasury_movement(p_type treasury_movement_type, p_date date, p_concept_id uuid, p_description text, p_payee text, p_amount numeric, p_legs jsonb, p_notes text) TO service_role;
GRANT EXECUTE ON FUNCTION public.read_gmail_credential() TO service_role;
GRANT EXECUTE ON FUNCTION public.reasignar_cliente_de_orden(p_work_order_id uuid, p_customer_id uuid) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.recalculate_all_sale_prices() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.receive_check(p_check jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rechazar_cotizacion_en_ot(p_quotation_id uuid) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_marca_modelo(p_marca text, p_modelo text, p_tamano text) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.registrar_tipo_de_pieza(p_tipo text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reject_check(p_check_id uuid, p_reason text, p_date date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.replace_quotation_items(p_quotation_id uuid, p_items jsonb) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.replace_work_order_items(p_work_order_id uuid, p_items jsonb) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.report_cash_book(p_from date, p_to date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.report_cash_count() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_checks_portfolio() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.report_customer_aging() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_customer_balances() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.report_customer_ranking(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_idle_stock(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_monthly_sales(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_retentions_applied(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_retentions_suffered(p_from date, p_to date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.report_sales_by_period(p_from date, p_to date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.report_stage_times(p_from date, p_to date) TO service_role, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.report_stale_prices() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_stock_valued() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_supplier_aging() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_supplier_balances() TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_top_articles(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_vat_purchases(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_vat_sales(p_from date, p_to date) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.report_work_order_margin(p_from date, p_to date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_price_authorization(p_work_order_id uuid) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.save_payment_order(p_header jsonb, p_allocations jsonb, p_values jsonb, p_new_provisional_credit_notes jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.save_purchase_invoice(p_header jsonb, p_items jsonb, p_taxes jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.save_receipt(p_header jsonb, p_allocations jsonb, p_values jsonb, p_changes jsonb) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.save_treasury_movement(p_header jsonb, p_legs jsonb) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.set_gmail_credential(p_password text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_preferred_supplier(p_article_id uuid, p_supplier_id uuid) TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.set_retention_certificate(p_receipt_value_id uuid, p_certificate_number text) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO authenticated, service_role, anon;
GRANT EXECUTE ON FUNCTION public.supplier_credit(p_supplier_id uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.sync_customer_phone() TO anon, service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.void_invoice(p_invoice_id uuid, p_reason text) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.void_payment_order(p_order_id uuid, p_reason text) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.void_purchase_invoice(p_purchase_invoice_id uuid, p_reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.void_receipt(p_receipt_id uuid, p_reason text) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.void_remito(p_remito_id uuid, p_reason text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.void_treasury_movement(p_movement_id uuid, p_reason text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.work_order_items_stock_sync() TO authenticated, service_role, anon;
